Document: openthread
Title: Debian openthread Manual
Author: <insert document author here>
Abstract: This manual describes what openthread is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openthread/openthread.sgml.gz

Format: postscript
Files: /usr/share/doc/openthread/openthread.ps.gz

Format: text
Files: /usr/share/doc/openthread/openthread.text.gz

Format: HTML
Index: /usr/share/doc/openthread/html/index.html
Files: /usr/share/doc/openthread/html/*.html
